export const data = [
  {
    id: 1,
    iconName: 'Tap',
    title: 'Plumbing',
    text: ['Install / Replace a Toilet', 'Install / Replace a Faucet', 'Fix a Leaking', 'Install / Replace a Sink', 'Repair Under Sink Plumbing'],
    color: '#169e2f',
  },
  {
    id: 2,
    iconName: 'paint',
    title: 'Drywall & painting',
    text: ['Install Drywall', 'Patch and Paint Drywall', 'Paint a Wall / Trim', 'Paint or Stain A Fence', 'Paint a Cabinet Door'],
    color: '#0278b8',
  },
  {
    id: 3,
    iconName: 'Frame11',
    title: 'Furniture assembly',
    text: ['Assemble Fitness Equipment', 'Assemble - Custom Request', 'Assemble a TV Stand', 'Assemble Pet Furniture', 'Assemble a Bar Cabinet'],
    color: '#f5af22',
  },
  {
    id: 4,
    iconName: 'Electrical',
    title: 'Electrical',
    text: ['Install / Replace a Ceiling Fan', 'Replace Switch & Outlet Faceplate', 'Upgrade to a Video Doorbell', 'Install / Replace an Bathroom Exhaust Fan'],
    color: '#f02b2b',
  },
  {
    id: 5,
    iconName: 'door',
    title: 'Doors & windows',
    text: ['Install / Replace New Door', 'Install / Replace a Screen Door', 'Install / Replace a Window Screen', 'Repair a Door Frame'],
    color: '#169e2f',
  },
  {
    id: 6,
    iconName: 'picture',
    title: 'Hanging & mounting',
    text: ['Mount a TV', 'Remove a TV Mount from Wall', 'Mount and Hang a Projector Screen', 'Hang a Bathroom Fixture'],
    color: '#0278b8',
  },
  {
    id: 7,
    iconName: 'instalation',
    title: 'Appliance instalation',
    text: ['Replace an Existing Dishwasher', 'Replace an Existing Microwave', 'Replace an Existing Oven'],
    color: '#f5af22',
  },
  {
    id: 8,
    iconName: 'home',
    title: 'Smart home',
    text: ['Install a Smart Lock', 'Install a Smart Home Security Camera', 'Mount a Baby Monitor Camera on the Wall', 'Install an Under Sink Water Filtration System '],
    color: '#f02b2b',
  },
  {
    id: 9,
    iconName: 'Tap(1)',
    title: 'Outdoor',
    text: [' Assemble an Outdoor Trampoline', 'Hang a Garage Shelving Unit', 'Install Outdoor Decorative Exterior Window Shutters', 'Install a Storm Door'],
    color: '#169e2f',
  },
]
